#!/bin/python3

import os
import sys
def getMoneySpent(keyboards, drives, b):
    #
    # Write your code here.
    keyboards=sorted(keyboards)
    drives=sorted(drives)
    if min(keyboards)+min(drives)>b:
        return -1
    m=len(keyboards)-1 
    n=len(drives)-1
    sum0=[]
    if max(keyboards)+max(drives)>b:
     for i in range (len(keyboards)):
        maxk=keyboards[i]
        for j in range(len(drives)):
         if drives[j]+maxk<=b:
            sum0.append(drives[j]+maxk)
         else:
             break
         
     return max(sum0)
         
    else:
        return max(drives)+max(keyboards)
             
            
        
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    bnm = input().split()

    b = int(bnm[0])

    n = int(bnm[1])

    m = int(bnm[2])

    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))

    #
    # The maximum amount of money she can spend on a keyboard and USB drive, or -1 if she can't purchase both items
    #

    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
